### ISSUE TITLE
Unable to find train and dev sets

### ISSUE THREAD

**Issue by vyaskaustubh** [UniversalDependencies/UD_Cantonese#2]
I was trying to compare some POS tagging models for different languages and as Cantonese has a very small class of Pronouns, I thought it might give some interesting results. However, I am unable to find the training and test conllu files. It would be really helpful if someone can guide me to them.

**Comment by martinpopel** [comment]
UD_Cantonese-HK has only 13918 tokens, so according to the [UD data-split guidelines](https://universaldependencies.org/release_checklist.html#data-split) all the data are released as [yue_hk-ud-test.conllu](https://github.com/UniversalDependencies/UD_Cantonese-HK/blob/master/yue_hk-ud-test.conllu) and 10-fold cross-validation is recommended for any experiments.

**Comment by vyaskaustubh** [comment]
Oh, thanks a lot.
I have never worked on a dataset with less than 20k words so I was unaware of this.
